---
date: 2024-01-26 00:57:51.652635-07:00
description: "\u0915\u0948\u0938\u0947 \u0915\u0930\u0947\u0902: Ruby \u092E\u0947\
  \u0902 `begin`, `rescue`, `ensure`, \u0914\u0930 `end` \u0915\u093E \u0909\u092A\
  \u092F\u094B\u0917 \u0915\u0930\u0915\u0947 \u090F\u0930\u0930\u094D\u0938 \u0915\
  \u094B \u0939\u0948\u0902\u0921\u0932 \u0915\u093F\u092F\u093E \u091C\u093E\u0924\
  \u093E \u0939\u0948\u0964 \u0906\u092A \u091C\u094B\u0916\u093F\u092E \u092D\u0930\
  \u0947 \u0915\u094B\u0921 \u0915\u094B `begin` \u0914\u0930 `end` \u0915\u0947 \u092C\
  \u0940\u091A \u092E\u0947\u0902\u2026"
lastmod: '2024-03-13T22:44:53.237049-06:00'
model: gpt-4-1106-preview
summary: "Ruby \u092E\u0947\u0902 `begin`, `rescue`, `ensure`, \u0914\u0930 `end`\
  \ \u0915\u093E \u0909\u092A\u092F\u094B\u0917 \u0915\u0930\u0915\u0947 \u090F\u0930\
  \u0930\u094D\u0938 \u0915\u094B \u0939\u0948\u0902\u0921\u0932 \u0915\u093F\u092F\
  \u093E \u091C\u093E\u0924\u093E \u0939\u0948\u0964 \u0906\u092A \u091C\u094B\u0916\
  \u093F\u092E \u092D\u0930\u0947 \u0915\u094B\u0921 \u0915\u094B `begin` \u0914\u0930\
  \ `end` \u0915\u0947 \u092C\u0940\u091A \u092E\u0947\u0902 \u0932\u092A\u0947\u091F\
  \u0924\u0947 \u0939\u0948\u0902\u0964 \u092F\u0926\u093F \u0915\u094B\u0908 \u090F\
  \u0930\u0930 \u0939\u094B\u0924\u093E \u0939\u0948, \u0924\u092C `rescue` \u0915\
  \u093E\u092E \u0915\u0930\u0924\u093E \u0939\u0948\u0964."
title: "\u090F\u0930\u0930\u094D\u0938 \u0915\u094B \u0939\u0948\u0902\u0921\u0932\
  \ \u0915\u0930\u0928\u093E"
weight: 16
---

## कैसे करें:
Ruby में `begin`, `rescue`, `ensure`, और `end` का उपयोग करके एरर्स को हैंडल किया जाता है। आप जोखिम भरे कोड को `begin` और `end` के बीच में लपेटते हैं। यदि कोई एरर होता है, तब `rescue` काम करता है।

```Ruby
begin
  # जोखिम भरा कोड यहाँ जाएगा।
  puts 10 / 0
rescue ZeroDivisionError => e
  puts "उफ़! आप ऐसा नहीं कर सकते: #{e.message}"
ensure
  puts "यह हमेशा चलेगा, चाहे एरर हो या ना हो।"
end
```

नमूना आउटपुट:
```
उफ़! आप ऐसा नहीं कर सकते: divided by 0
यह हमेशा चलेगा, चाहे एरर हो या ना हो।
```

## गहन अध्ययन
ऐतिहासिक रूप से, प्रोग्रामिंग भाषाओं में एरर हैंडलिंग काफी विकसित हुई है, जहाँ पहले की भाषाओं में अक्सर साधारण या गैर-मौजूद तंत्र होते थे। Ruby की एक्‍सेप्शन हैंडलिंग Python और Smalltalk जैसी भाषाओं से प्रेरित है।

Ruby में `begin-rescue` के विकल्पों में विधि परिभाषाओं में `rescue` का उपयोग या गैर-मानक फ्लो कंट्रोल के लिए `throw` और `catch` का उपयोग करना शामिल है, हालांकि उनका उपयोग सामान्य एरर हैंडलिंग के लिए नहीं किया जाता है।

एक दिलचस्प विवरण: Ruby में अपवाद (एक्सेप्शन) ऑब्जेक्ट होते हैं (Exception क्लास और उसके वंशजों के उदाहरण), इसलिए आप कस्टम एरर क्लासेस को परिभाषित कर सकते हैं और सिर्फ एरर्स को लॉग करने से ज्यादा कर सकते हैं - आप प्रोग्राम के चारों ओर समृद्ध स्थिति ले जा सकते हैं, जो और अधिक मजबूत एरर हैंडलिंग के लिए है।

## देखें भी
- अपवादों और एरर हैंडलिंग पर Ruby दस्तावेज़: [ruby-doc.org](https://ruby-doc.org/core-3.1.0/doc/syntax/exceptions_rdoc.html)
- Ruby एरर हैंडलिंग की बेहतरीन प्रैक्टिसेज पर विस्तारित गाइड: [thoughtbot.com](https://thoughtbot.com/blog/rescue-standarderror-not-exception)
